      SUBROUTINE CMP2VC(VEC1,VEC2,NDIM,THRES)
C
C COMPARE TWO DOUBLE PRECISION  VECTORS VEC1,AND VEC2
C
C ONLY ELEMENTS THAT DIFFERS BY MORE THAN THRE ARE PRINTED
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION VEC1(1),VEC2(1)
C
      XMXDIF = 0.0D0
      IMXPLC = 0
      WRITE(6,*) ' COMPARISON OF TWO VECTORS '
      WRITE(6,*) '      VECTOR1      VECTOR2        DIFFERENCE '
      DO 100 I = 1, NDIM
        DIF = VEC1(I) - VEC2 ( I )
        IF( ABS(DIF ) .GE. XMXDIF ) THEN
          XMXDIF = ABS(DIF)
          IMXPLC = I
        END IF
        IF( ABS ( DIF ) .GT. THRES ) THEN
          WRITE(6,'(2X,I5,3E15.8)') I,VEC1(I),VEC2(I),DIF
        END IF
  100 CONTINUE
C
      IF( XMXDIF .EQ. 0.0D0 ) THEN
        WRITE(6,*) ' THE TWO VECTORS ARE IDENTICAL '
      ELSE
        WRITE(6,*) ' SIZE AND LAST PLACE OF LARGEST DEVIATION ',
     &  XMXDIF,IMXPLC
      END IF
C
      RETURN
      END
