      SUBROUTINE DIAVC2(VECOUT,VECIN,DIAG,SHIFT,NDIM)
C
C VECOUT(I)=VECIN(I)/(DIAG(I)+SHIFT)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION VECOUT(1),VECIN(1),DIAG(1)
C
      DO 100 I=1,NDIM
      DIVIDE=DIAG(I)+SHIFT
      THRES=1.0D-10
      IF(ABS(DIVIDE).LE.THRES) DIVIDE=THRES
      IF(VECIN(I).EQ.0.0D0) THEN
        VECOUT(I) = 0.0D0
      ELSE
        VECOUT(I)=VECIN(I)/DIVIDE
      END IF
  100 CONTINUE
      RETURN
      END
