       SUBROUTINE MGS(NDIM,NVECIN,IVCFIL,NVECUT
     +    ,X,A1,A2,B1,B2,MAXVEC)
C
C SUBROUTINE FOR MODIFIED GRAM SCHMIDT ORTHONORMALIZATION.CARE
C HAS BEEN TAKEN IN ORDER TO ASSURE STABLE NUMERICAL PERFORMANCE
C JO 10 MARCH '86
C
C THE NVECIN INPUT VECTORS RESIDE ON  DISCFILE IVCFIL WITH A SPACING OF
C THE NVECUT ORTHOGONALIZED VECTORS IS DESCRIBED BY MATRIX X: X(OLDVEC,N
C THE UNIT BASIS  IS ASSUMED ORTHOGONAL.
C
C
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      REAL * 8   INPROD
C
      DIMENSION A1(1  )   ,A2(1     ),B1(1   ),B2(1   )
      DIMENSION X(MAXVEC,MAXVEC)
C
      NTEST=1
      IF(NVECIN.GT.MAXVEC) THEN
       WRITE(6,1011)NVECIN,MAXVEC
 1011  FORMAT(1H0,' ACTUAL SUBSPACE DIMENSION',I3,
     +        ' GREATER THAN ALLOWED MAXIMUM',I3,'!!!!!')
       STOP
      END IF
C
C
       XMAX = 1.0D+06
       IEFF = 0
       DO 10 I = 1,NVECIN
        DO 9 J = 1,NVECIN
    9  X(I,J)=0.0D0
   10  X(I,I)=1.0D0
C
C LOOP OVER NEW VECTORS
       DO 600 I=1,NVECIN
C**     UNNORMALIZED VECTOR I
        ISTOP = I
        IADD  = 1
        IMULT = 2
        CALL SETVEC (B1,0.0D0,NDIM)
        CALL VECSMF(B1,X(1,I),B2,ISTOP,IMULT,IADD,IVCFIL,NDIM)
C**     NORMALIZE
        BNORM = INPROD(B1,B1,NDIM)
        SCALE = 1.0D0/SQRT(BNORM)
        CALL SCALVE(B1,SCALE,NDIM)
        CALL SCALVE(X(1,I),SCALE,NVECIN)
C        WRITE(6,*) ' I X(*,I) ',I
C        CALL WRITVE( X(1,I),NVECIN)
        XLARGE = FNDMNX(X(1,I),NVECIN,2)
        IF( ABS(XLARGE) .LE. XMAX ) THEN
C**      NEW VECTOR IS OKAY SO
         IEFF = IEFF + 1
         IF( IEFF .NE. I ) CALL COPVEC(X(1,I),X(1,IEFF),NVECIN)
C**      ORTHOGONALIZE REMAINING VECTORS TO THIS VECTOR
         IPL1 = I + 1
C*       OVERLAP BETWEEN NEW VECTOR AND ORIGINAL VECTORS
         CALL REWINO( IVCFIL)
         DO 500 J=1,NVECIN
          IF( J.NE.1) READ(IVCFIL)
          CALL FRMDSC(B2,NDIM,-1  ,IVCFIL,IMZERO,IAMPACK)
          A1(J)=INPROD(B1,B2,NDIM)
          CALL MATVCB(X,A1,A2,MAXVEC,NVECIN,1)
  500    CONTINUE
C*       ORTHOGONALIZE
         DO 450 K=IPL1,NVECIN
          FAC1 = 1.0D0/(1.0D0 - A2(K)**2)
          FAC2=  -A2(K)*FAC1
          CALL VECSUM(X(1,K),X(1,K),X(1,IEFF),FAC1,FAC2,NVECIN)
  450   CONTINUE
       END IF
  600 CONTINUE
C
C
      NVECUT = IEFF
      IF( NVECUT.NE.NVECIN)
     + WRITE(6,1010 ) NVECUT
 1010 FORMAT(1H0,' number of vectors reduced to..',I4)
      RETURN
      END
