#!/bin/bash

MOLPRO=$HOME/programs/Molpro
TESTJOB=$HOME/programs/GeCCo/itf_autestjobs

cd ../
make -j4
cd $TESTJOB

for dir in */; do
    dir=${dir%*/}
    echo $dir

    cd $dir
    rm auicmrcc_${dir}.itfaa
    gecco.x ccd.inp > ccd.out

    echo "Results for icmrcc_${dir}:"
    diff auicmrcc_${dir}.itfaa example.itfaa

    echo "Molpro results:"
    cp auicmrcc_${dir}.itfaa $MOLPRO/src/algo/
    cd $MOLPRO
    make -j4 > /dev/null

    cd $TESTJOB/${dir}
    rm test.err
    molpro -s test.molpro
    grep 'ERRORS' test.err
    echo
    echo
    cd $TESTJOB
done
